# Generated by Django 3.2.9 on 2021-11-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts_quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('element', models.CharField(blank=True, max_length=255, null=True)),
                ('traits', models.CharField(blank=True, max_length=255, null=True)),
                ('founder', models.CharField(blank=True, max_length=255, null=True)),
                ('commonroom', models.CharField(blank=True, max_length=255, null=True)),
                ('ghost', models.CharField(blank=True, max_length=255, null=True)),
                ('students', models.IntegerField(blank=True, null=True)),
                ('gryffindor', models.IntegerField(blank=True, null=True)),
                ('hufflepuff', models.IntegerField(blank=True, null=True)),
                ('ravenclaw', models.IntegerField(blank=True, null=True)),
                ('slytherin', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
