# Generated by Django 3.2.9 on 2021-11-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts_quiz', '0004_auto_20211114_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='name_smallcaps',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
