# Generated by Django 3.2.9 on 2021-11-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts_quiz', '0005_house_name_smallcaps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='number',
        ),
    ]
