# Generated by Django 3.2.9 on 2021-11-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts_quiz', '0007_result_selected_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
