# Generated by Django 3.2.9 on 2021-11-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts_quiz', '0008_house_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='keywords',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
