# Generated by Django 3.2.9 on 2021-11-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts_quiz', '0009_alter_house_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='name_smallcaps',
        ),
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
