# Generated by Django 3.2.9 on 2021-11-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts_quiz', '0012_house_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='selected_others',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='satisfaction',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
