# Generated by Django 3.2.9 on 2021-11-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts_quiz', '0013_auto_20211121_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='satisfaction_rate',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
